name: pos_pinch_zoom_image
description: A widget that makes picture pinch zoom, then return back to initial size and position when released.
version: 0.2.0
author: Ramin Najjarbashi <ramin.najarbashi@gmail.com>
homepage: https://github.com/ossolution/pinch_zoom_image

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.5.0

flutter:
  plugin:
    androidPackage: com.shatsy.pinchzoomimage
    pluginClass: PinchZoomImagePlugin
